### ISSUE TITLE
Implement the intro cutscene

### ISSUE THREAD

**Issue by superusercode** [PokemonUnity/PokemonUnity#11]
Any suggestions toward implementation?

**Comment by gerd2002** [comment]
Maybe just a video playing?

**Comment by TeamPopplio** [comment]
This is an old topic but I should comment on it. I have successfully implemented an intro cutscene but it requires a lot of changes made in develop, so I can't actually commit it to master. Though I was looking forward to committing it to develop soon. It's fully functional but has a bug and is missing the professor/pokemon animation.

**Comment by TeamPopplio** [comment]
The inclusion of the finalized intro cutscene (missing some animations but otherwise functional) has been committed into the develop branch and therefore this issue is resolved, however I will leave it open as I'm not sure if we could use this as a discussion board (though I recommend using r/PokemonUnity or the discord instead)

**Comment by GMR516** [comment]
I'm sure the implementation we have now is great until the end of development. Let's close it.
